node:
  node_id: "node1"
  address: "localhost:9000"
  data_dir: "./data/node1"
  max_mem_items: 1000
  quorum:
    n: 3  # Replication factor
    r: 2  # Read quorum
    w: 2  # Write quorum
  cluster_nodes:
    - "localhost:9001"
    - "localhost:9002"

api:
  port: 8080

log:
  level: "info"
  format: "text" 